# Generated by Django 2.2.16 on 2020-09-29 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='画像')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StyleCategory', verbose_name='スタイルカテゴリ')),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stylist', verbose_name='スタイリスト')),
            ],
        ),
    ]
