# Generated by Django 2.2.16 on 2020-10-02 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
