# Generated by Django 2.2.16 on 2020-10-08 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0005_auto_20201009_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchaser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaser_name', models.CharField(max_length=50)),
                ('purchaser_furigana', models.CharField(max_length=50)),
                ('purchaser_adress', models.CharField(max_length=150)),
                ('purchaser_tel', models.CharField(max_length=50)),
                ('purchaser_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='purchaser_adress',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='purchaser_email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='purchaser_furigana',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='purchaser_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='purchaser_tel',
        ),
        migrations.AddField(
            model_name='payment',
            name='purchaser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ec.Purchaser', verbose_name='購入者情報'),
            preserve_default=False,
        ),
    ]
