# Generated by Django 2.2.16 on 2020-09-28 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200928_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'stylist', 'verbose_name_plural': 'stylists'},
        ),
    ]
